### ISSUE TITLE
Update pipeline with official docker github actions

### ISSUE THREAD

**Issue by kayoumido** [Underflowers/Stack-Underflow#44]
```
  - name: Set up Docker build
      uses: docker/setup-buildx-action@v1

  - name: Login to github container
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: hans-arn
        password: ${{ secrets.OPENAFFECT_PAT }}

  - name : push on ghcr
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/groupe-amt/project_1:latest
        cache-from: type=ghcr.io,ref=ghcr.io/groupe-amt/project_1:latest
        cache-to: type=inline
```
